---

apiVersion: "v1"
kind: "Service"

metadata:
  name: "yss"
  labels:
    app: "yss"

spec:

  selector:
    app: "yss"
  # NodePort is needed to see the real client ip address
  type: "NodePort"
  externalTrafficPolicy: "Local"
  ports:
    - port: {{ $.Values.ListenPort }}

