---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yss
  labels:
    app: yss

spec:

  selector:
    matchLabels:
      app: yss

  template:
    metadata:
      name: yss
      labels:
        app: yss
      annotations:
        checksum/configmap: {{ include ( print $.Template.BasePath "/" "configmap.yaml" ) . | sha256sum }}

    spec:

      volumes:
        - name: data-dir
          hostPath:
            path: "{{ $.Values.DataDir }}"
            type: DirectoryOrCreate

      containers:

        - name: yss
          image: "{{ $.Values.ImageNameGithubYss }}:{{ $.Values.ImageTagGithubYss }}"
          imagePullPolicy: IfNotPresent

          volumeMounts:
            - name: data-dir
              mountPath: "{{ $.Values.DataDir }}"

          ports:
            - containerPort: {{ $.Values.ListenPort }}

          envFrom:
            - configMapRef:
                name: yss


