
apiVersion: "apps/v1"
kind: "StatefulSet"

metadata:
  name: "yss"
  labels:
    app: "yss"

spec:

  selector:
    matchLabels:
      app: "yss"

  template:
    metadata:
      name: "yss"
      labels:
        app: "yss"
      annotations:
        checksum/configmap: "{{ include ( print $.Template.BasePath "/" "configmap.yaml" ) . | sha256sum }}"

    spec:

      volumes:
        - name: "data-dir"
          hostPath:
            path: "{{$.Values.DataDir}}"
            type: "DirectoryOrCreate"
        - name: "zoneinfo"
          hostPath:
            path: "/usr/share/zoneinfo/"
            type: "Directory"
        - name: "localtime"
          hostPath:
            path: "/etc/localtime"
            type: "File"

      containers:

        - name: "yss"
          image: "{{$.Values.ImageNameGithubYss}}:{{$.Values.ImageTagGithubYss}}"
          imagePullPolicy: "IfNotPresent"

          volumeMounts:
            - name: "data-dir"
              mountPath: "{{$.Values.DataDir}}"
            - name: "zoneinfo"
              mountPath: "/usr/share/zoneinfo/"
              readOnly: true
            - name: "localtime"
              mountPath: "/etc/localtime"
              readOnly: true

          ports:
            - containerPort: {{$.Values.ListenPort}}

          envFrom:
            - configMapRef:
                name: "yss"



