# https://github.com/bsord/helm-push
# https://docs.github.com/en/actions/learn-github-actions/contexts

name: helm

permissions:
  packages: write
  contents: read

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'helm/**'
      - '.github/workflows/helm.yaml'

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:

      - name: version
        run: echo "VERSION=$( date '+%y.%m%d.%H%M' | sed 's/\.0*/./g' )" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: chart version
        run: |
          sed -i -e "s/__VERSION__/$VERSION/g" helm/Chart.yaml
          cat helm/Chart.yaml

      - uses: bsord/helm-push@v4
        with:
          useOCIRegistry: true
          registry-url:  oci://ghcr.io/${{ github.repository }}/${{ github.ref_name }}
          username: ${{ github.repository_owner }}
          access-token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          chart-folder: helm


